#!/bin/bash
set -u

function display_file() {
    echo -e "\n#==[ Configuration File ]===========================#"
    echo -e "# ${1}"
    cat "${1}"
}


function display_rpm() {
    echo -e "\n#==[ Command ]======================================#"
    echo -e "# rpm -q ${1} "
    rpm -q "${1}"
}

function display_cmd() {
    echo -e "\n#==[ Command ]======================================#"
    echo -e "# ${@}"
    ${@}
}

function display_cgroup() {
    local f
    echo -e "\n#==[ Cgroup ]=======================================#"
    for f in memory.low memory.current memory.stat memory.events ; do
        echo "# ${1}/${f}"
        cat ${1}/${f}
        echo
    done
}

function display_log() {
    local file
    echo -e "\n#==[ Log File ]=====================================#"
    for file in ${1} ; do
        if [ -n "${3-}" ] ; then
            echo -e "# ${file} - only pattern '${2}' (latest ${3} hits)"
            zgrep "${2}" "${file}" | tail -n "${3}"
        else
            echo -e "# ${file} - only pattern '${2}'"
            zgrep "${2}" "${file}"
        fi
    done
}

function display_instance_profiles() {
    local p profile
    echo -e "\n#==[ Configuration]================================#"

    # Extracts profile pathes from running processes.
    while read profile ; do
        [[ "${profile}" =~ /host_profile ]] && continue
        echo "# ${profile}"
        cat "${profile}"
        echo
    done < <(
        while read p ; do
            [ "${p:0:3}" = "pf=" ] || continue
            echo "${p:3}"
        done < <(ps -eo cmd | tr ' ' '\n') | sort -u )
}

function display_swapped_procs() {
    local path pid comm swappss
    echo -e "\n#==[ Configuration ]================================#"
    echo "# /proc/[0-9]*/smaps - only SwapPSS > 0"
    printf "      SwapPss  Process\n-------------  ---------------------------\n"
    for path in /proc/[1-9]* ; do
        # smaps take time, tolerate gone PIDs
        [ -d ${path} ] || continue
        pid="${path##*/}"
        read comm < /proc/${pid}/comm
        swappss=$(awk 'BEGIN { swappss = 0 } /^SwapPss:/ { swappss += $2 } END {print swappss}' "${path}/smaps")
        [ "0${swappss}" -eq 0 ] && continue
        printf "%10d kB  %s[%d]\n" "${swappss}" "${comm}" ${pid}
    done
}


# ---- Main ----
display_cmd grep cgroup /proc/mounts
display_file /proc/cmdline
display_file /etc/default/grub
display_rpm sapwmp
display_file /etc/sapwmp.conf
display_cmd systemctl cat sap.slice
display_cmd systemctl show -p MemoryLow sap.slice
display_cmd systemctl status wmp-sample-memory.timer
display_cmd systemctl cat wmp-sample-memory.timer
display_instance_profiles
display_cmd systemd-cgls --all --no-pager
display_cgroup /sys/fs/cgroup/sap.slice
display_cgroup /sys/fs/cgroup/system.slice
display_cgroup /sys/fs/cgroup/user.slice
display_cgroup /sys/fs/cgroup/init.scope
display_swapped_procs
display_log '/var/log/messages*' sapwmp-capture
display_log '/var/log/messages' wmp_memory_current 10

# Bye.
exit 0

